### ISSUE TITLE
Quadratic Weighted Kappa

### ISSUE THREAD

**Issue by Nosferican** [JuliaML/LossFunctions.jl#107]
Feature Request: Add [quadratic weighted kappa](https://www.kaggle.com/c/petfinder-adoption-prediction#evaluation) loss function.

**Comment by juliohm** [comment]
@Nosferican can you draft a PR with the loss? We are happy to review it.

**Comment by juliohm** [comment]
Closing as inactive. Feel free to start a new issue based on the current design of the package.
