### ISSUE TITLE
Please don't export all of LearnBase

### ISSUE THREAD

**Issue by ablaom** [JuliaML/LossFunctions.jl#112]
There doesn't seem to be any sense in re-exporting functions with no methods:

```julia
julia> using LossFunctions

julia> transform
transform (generic function with 0 methods)
```
Ditto `transform!`. This is causing conflicts in use of [MLJ]() which exports a transform that actually has methods. That is, if I do "using LossFunctions" when using MLJ, then my `transform` methods now have to be prefixed with `MLJ`.

**Comment by juliohm** [comment]
This can be closed apparently.
