### ISSUE TITLE
Support for categorical arrays

### ISSUE THREAD

**Issue by juliohm** [JuliaML/LossFunctions.jl#117]
Could you please comment on the support for categorical arrays from CategoricalArrays.jl?

If they are not supported, can I submit a PR to add support?

**Comment by joshday** [comment]
I believe categorical losses assume your data is coded -1 or 1.  If you have a CategoricalArray with those values that should work.  I don't believe Arrays are hard coded in anywhere.

**Comment by juliohm** [comment]
I don't think it is working @joshday. See the example below, even with -1/1 codding:

```Julia
using LossFunctions
using CategoricalArrays

a = categorical([-1,1,-1])
b = categorical([-1,1,1])

value(ZeroOneLoss(), a, b, AggMode.Mean()) # misclassification rate

MethodError: no method matching one(::Type{CategoricalValue{Int64,UInt32}})
Closest candidates are:
  one(!Matched::Type{Missing}) at missing.jl:103
  one(!Matched::BitArray{2}) at bitarray.jl:400
  one(!Matched::Missing) at missing.jl:100
  ...

Stacktrace:
 [1] value(::ZeroOneLoss, ::CategoricalArray{Int64,1,UInt32,Int64,CategoricalValue{Int64,UInt32},Union{}}, ::CategoricalArray{Int64,1,UInt32,Int64,CategoricalValue{Int64,UInt32},Union{}}, ::LossFunctions.AggMode.Sum) at /Users/julio.hoffimann@ibm.com/.julia/packages/LossFunctions/VQQPk/src/supervised/supervised.jl:312
 [2] top-level scope at In[1]:7
```

I can make it work for categorical arrays with:

```Julia
import LossFunctions

LossFunctions.value(loss::ZeroOneLoss, ŷ::CategoricalValue, y::CategoricalValue) =
  levelcode(ŷ) == levelcode(y) ? 0 : 1

value(ZeroOneLoss(), a[1], b[1]) # equals 0
value(ZeroOneLoss(), a[3], b[3]) # equals 1
```

But the aggregation functionality still does not work:

```Julia
value(ZeroOneLoss(), a, b, AggMode.Mean()) # misclassification rate

# same error one(CategoricalValue...) not defined
```

Can you please advise on how to make it work? This is the minimum urgent change I need to get the paper going.

**Comment by juliohm** [comment]
In particular, I can live with just the `ZeroOneLoss` for multi-class variables for now. This is the only loss I am planning to report in this paper for now.

**Comment by joshday** [comment]
I won't have time for a while to look at this.  Your best bet is finding the method you're calling with `@which` and fixing it.

**Comment by juliohm** [comment]
What about the modification to the `ZeroOneLoss` itself? I found it in the margin.jl source but it is only defined in terms of the agreement: https://github.com/JuliaML/LossFunctions.jl/blob/master/src/supervised/margin.jl#L43

Where is the fallback definition for `value(loss, target, output)` in the source? I could add the method I've added above for categorical values, and then try to fix the generated functions in supervised.jl

**Comment by juliohm** [comment]
I think we could move the `ZeroOneLoss` to another family of losses which is not margin-based. It also works for multi-class where this notion of margin as the product of target*output does not hold.
