### ISSUE TITLE
[docs] links dead

### ISSUE THREAD

**Issue by ptoche** [JuliaML/LossFunctions.jl#141]
Many of the links [here](https://github.com/JuliaML/LossFunctions.jl/blob/master/docs/src/user/aggregate.md) are dead: they end in `@ref`. For instance, the very first one, linking from `value` is: 

https://github.com/JuliaML/LossFunctions.jl/blob/master/docs/src/user/@ref

**Comment by Evizero** [comment]
These are the source files of the documentation. They are primarily for authoring said docs. 
Its best viewed using github pages.  e.g. this is the corresponding page of your link: https://juliaml.github.io/LossFunctions.jl/stable/user/aggregate/

**Comment by ptoche** [comment]
Thanks. 👍 

Blame my search engine!
