### ISSUE TITLE
No difference between `WeightedMean` and `WeighedSum` when `normalize=false`

### ISSUE THREAD

**Issue by ablaom** [JuliaML/LossFunctions.jl#149]
This looks like a bug to me:

```julia
julia> y = rand(3); yhat = rand(3); w = rand(3);

julia> value(L1DistLoss(), y, yhat, AggMode.WeightedMean(w, normalize=false))
0.4515037807304132

julia> value(L1DistLoss(), y, yhat, AggMode.WeightedSum(w, normalize=false))
0.4515037807304132
```

I believe the problem is with weighted mean:

```julia
julia> value(L1DistLoss(), [1, 2, 3], [2, 5, -2], AggMode.WeightedMean([1, 2, 1], normalize=false))
12.0
```

The unweighed distances are `[1, 3, 1]`. So the weighted distances are `[1, 6, 1]`, which has mean `8/3` not `12`, right?

**Comment by juliohm** [comment]
Definitely a bug @ablaom , sorry for only seeing this issue now. I am revamping the package for a new minor release and will try to fix this right away.

**Comment by ablaom** [comment]
@juliohm Friendly reminder.
