### ISSUE TITLE
Release tags on repo are not up to date with General.jl

### ISSUE THREAD

**Issue by ablaom** [JuliaML/LossFunctions.jl#152]
https://github.com/JuliaAI/MLJBase.jl/pull/772#issuecomment-1134135814

**Comment by ablaom** [comment]
Also, please, where are the release notes for 0.8?

**Comment by juliohm** [comment]
Thank you @zsz00 for pinging, I was unaware of this issue.

@ablaom I think the tag bot will generate the release notes. We just removed the dependency on LearnBase.jl and also dropped some old deprecation warnings.

**Comment by juliohm** [comment]
I've updated the TagBot file. Let's see if the release will show up in a few minutes. Otherwise I will see what I need to do.

**Comment by juliohm** [comment]
Tag is now available.
