### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by gustavdelius** [JuliaML/LossFunctions.jl#166]
Currently the [documentation](https://juliaml.github.io/LossFunctions.jl/stable/) is still for version 0.5.0 while we are already on 0.10.0 and there have been a lot of changes.

**Comment by juliohm** [comment]
Thank you @gustavdelius for reporting the issue. Any help is appreciated, I am super busy this week and the next.

**Comment by juliohm** [comment]
The documentation has been updated automatically by the bots now.
