### ISSUE TITLE
Convert CategoricalArrays.jl to extension?

### ISSUE THREAD

**Issue by MilesCranmer** [JuliaML/LossFunctions.jl#167]
Currently the CategoricalArrays.jl dependency is fairly costly in terms of load time. Despite LossFunctions.jl itself only taking 6.5ms to load, the CategoricalArrays dependency takes 100ms. But from looking through the code, the CategoricalArrays.jl is more of an extension rather than a core library used in the code.

So perhaps it could be converted into a dependency to cut down on load times?

**Comment by juliohm** [comment]
Good idea @MilesCranmer , can you submit a PR that requires Julia v1.9 and implements the proposal?

**Comment by MilesCranmer** [comment]
Done in #168.

It uses Requires.jl for lower Julia versions, for backwards compatibility.

**Comment by juliohm** [comment]
Patch released: https://github.com/JuliaRegistries/General/pull/88036
