### ISSUE TITLE
Very slow loss aggregation

### ISSUE THREAD

**Issue by MilesCranmer** [JuliaML/LossFunctions.jl#172]
The `mean` and `sum` implementations in this package are extremely slow as they rely on generators. Could this be changed to a faster implementation? For example, here is how the current implementation would compute sum-squared-error:

```julia
square(x) = x ^ 2

# example of generator-based approach:
function sse(outputs, targets)
    sum(square(ŷ - y) for (ŷ, y) in zip(outputs, targets))
end
```

(i.e., like [this code](https://github.com/JuliaML/LossFunctions.jl/blob/7318c582874988fcc325464831aa2ce94eb36ff2/src/losses.jl#L37-L39))

which gives us the following time:

```julia
julia> @btime sse(outputs, targets) setup=(outputs=randn(100_000); targets=randn(100_000))
  92.833 μs (0 allocations: 0 bytes)
```

but if we change this to an approach using `sum(<function>, <indices>)`, it's much faster:

```julia
function sse2(outputs, targets)
    sum(i -> square(outputs[i] - targets[i]), eachindex(outputs, targets))
end
```

```julia
julia> @btime sse2(outputs, targets) setup=(outputs=randn(100_000); targets=randn(100_000))
  26.708 μs (0 allocations: 0 bytes)
```

which is a 3.5x speedup.

Could this be implemented as the default loss calculation? I thought this was the method that used to be used. Perhaps it got changed in the recent refactoring?

**Comment by juliohm** [comment]
I don't remember using this feature anywhere else in downstream packages.
If you can submit a PR dropping support for generators, we can review and
merge it.

Em qui., 24 de ago. de 2023 04:31, Miles Cranmer ***@***.***>
escreveu:

**Comment by MilesCranmer** [comment]
> I don't remember using this feature anywhere else in downstream packages.

Sorry I don't think I was clear. This is the main `sum` function in LossFunctions.jl which is the main interface to the package. It seems to be using a generator (e.g., `sum(f(x) for x in X)`) for summing, which is very slow:

https://github.com/JuliaML/LossFunctions.jl/blob/7318c582874988fcc325464831aa2ce94eb36ff2/src/losses.jl#L37-L39

> If you can submit a PR dropping support for generators, we can review and merge it.

Sure!

**Comment by MilesCranmer** [comment]
Implemented in https://github.com/JuliaML/LossFunctions.jl/pull/173

**Comment by juliohm** [comment]
Yes, i meant using the version with generators in downstream packages that
depend on LossFunctions.jl

Em qui., 24 de ago. de 2023 05:49, Miles Cranmer ***@***.***>
escreveu:

**Comment by MilesCranmer** [comment]
Got it, thanks!
