### ISSUE TITLE
Code examples in "Getting Started" don't seem to work

### ISSUE THREAD

**Issue by alex-s-gardner** [JuliaML/LossFunctions.jl#174]
```julia
using LossFunctions
L2DistLoss()(0.5, 1.0)

ERROR: MethodError: no method matching (::L2DistLoss)(::Float64, ::Float64)
Stacktrace:
 [1] top-level scope
   @ REPL[35]:1
```

Same issue for other examples as well

**Comment by alex-s-gardner** [comment]
It looks like loss functions now accept vector inputs and do not use dispatch

**Comment by juliohm** [comment]
Can't reproduce the error. Are you positive that you are using the latest version?

**Comment by alex-s-gardner** [comment]
@juliohm you are very correct... not sure what was going on there. I must have been using an older version of LossFunctions. 

It works fin with LossFunctions v0.11.1, apologies
