### ISSUE TITLE
Add min and argmin to losses

### ISSUE THREAD

**Issue by ahwillia** [JuliaML/LossFunctions.jl#35]
At the moment the minimum of the `PoissonLoss` is non-zero. This does not change the answer to whatever optimization problem you are solving, so I am inclined to leave it as is for now. 

If we decided we want the convention to be zero loss for perfect fit, we'd have to make the following change:

``` julia
# current:
value(::PoissonLoss, t::Number, o::Number) = exp(o) - t*o

# add a shift:
value(::PoissonLoss, t::Number, o::Number) = exp(o) - t*o + t*log(t) - t
```

This convention may have some advantages, but I'd have to think carefully about it. A downside is that it adds potentially unnecessary computations.

**Corallary:** If we don't do the re-shifting, it might be nice to add some functions:

``` julia
minimum(::PoissonLoss, target::Number) = t*log(t) - t   # best achievable value
argmin(::PoissonLoss, target::Number) = log(t)          # value of output to achieve min
```

**Comment by Evizero** [comment]
I can't think of a good reason that the value of a loss has to be zero at the minimum. A loss value is somewhat arbitrary anyway. The important thing is the derivative

I don't see a downside to having the two functions you are proposing. So if they are useful to you we can add them

**Comment by Evizero** [comment]
we should rename this issue to update its intend. was about to close it right now :)

**Comment by Evizero** [comment]
concerning `argmin` how would we handle truncated losses, such as the hinge loss, that don't have a unique global minimum?

**Comment by tbreloff** [comment]
Isn't it already? I'll have to check.

**Comment by Evizero** [comment]
Concerning shifting. I encountered a little discussion on shifted loss functions [here](http://www.stoch.uni-bayreuth.de/de/CHRISTMANN/Christmann_files/ChristmannEtAl2009.pdf) on page 3. That said, this does not seem interesting for practical purposes as far as I can tell

**Comment by ahwillia** [comment]
I tend to agree this is low priority but would still be nice to provide. If you are interpreting the loss function as the negative-log-likelihood function, then you need to apply the shift. Machine learning people probably don't care, but statisticians might.

**Comment by Evizero** [comment]
Fair point. We could make it into an issue titled "ShiftedLoss" (or something like that) as a bookmark if you want

**Comment by ahwillia** [comment]
I think having `min` and `argmin` would suffice. I just need to get around to it.

**Comment by Mine8801** [comment]
https://github.com/JuliaML/LossFunctions.jl/issues/35#issuecomment-248556310

**Comment by juliohm** [comment]
I agree this issue is not a priority. It was opened in 2016 before Julia v0.5, and I don't think we have very strong reasons to add more names to the API without a clear benefit.
