### ISSUE TITLE
Pinball Loss

### ISSUE THREAD

**Issue by Evizero** [JuliaML/LossFunctions.jl#42]
We should also implement the Pinball loss aka Quantile Loss. (see p. 44, example 2.43 in Steinwart 2008)
- Steinwart, Ingo, and Andreas Christmann. Support vector machines. Springer Science & Business Media, 2008.

**Comment by Evizero** [comment]
This is currently in progress by josh here: https://github.com/JuliaML/LossFunctions.jl/tree/josh

**Comment by joshday** [comment]
I don't think I ever saw this issue...I'll submit a PR soon.

**Comment by joshday** [comment]
QuantileLoss is now in master.
