### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by Evizero** [JuliaML/LossFunctions.jl#46]
We have a rudimentary documentation in place, but it could be a lot better.
- More description text for each loss
- Formula for derivative for each loss (?)

**Comment by ahwillia** [comment]
We should add documentation for `grad!`, `grad`, `deriv`, etc.  I assume it should be done here, and not in LearnBase? cc @tbreloff

**Comment by tbreloff** [comment]
I think LearnBase should have documentation on the "intended meaning" of
the verbs. For example that grad will return a gradient vector with respect
to some loss (it's confusing for example that I'd expect 'grad' of an
affine transformation to be the gradient wrt params 'CatView(w, b)', but in
Losses it might return the gradient of the input vector x). I think it
would help us to agree on those meanings, and maybe have distinct verbs if
they truly are different.

Docs for loss-specific things should be in Losses.

**Comment by ahwillia** [comment]
Yeah that makes more sense.

**Comment by Evizero** [comment]
I agree on documentation in general, but where do you guys see the `grad` function? Maybe the way to go is go one by one through the interface and list those methods that are not yet covered by http://lossesjl.readthedocs.io/en/latest/losses/interface.html . I do think I got most of them, but the main intention opening this issue was that they could be a little more elaborate

**Comment by Evizero** [comment]
We should also at some point add a "heatmap"-like table for the losses and their properties as suggested by tom in https://github.com/JuliaML/Losses.jl/pull/53#issuecomment-251953910
