### ISSUE TITLE
Distance Weighted Discrimination MarginLoss

### ISSUE THREAD

**Issue by joshday** [JuliaML/LossFunctions.jl#54]
DWD is a differentiable generalization of L1HingeLoss (but different from SmoothedL1HingeLoss).  Is `DWDMarginLoss` a good enough name?

See page 11.  https://arxiv.org/pdf/1508.05913.pdf

**Comment by Evizero** [comment]
I think `DWDLoss` may be enough, although now that I see it written i do like `DWDMarginLoss` more. This looks like an interesting paper I surely need to read. 

It looks straight forward to implement, both the `value` and the `deriv` are specified. This looks like a good introduction issue.
