### ISSUE TITLE
Handling binary sparse vectors and arrays

### ISSUE THREAD

**Issue by ahwillia** [JuliaML/LossFunctions.jl#56]
I think there are a lot of issues for handling sparse data. The main one I want to highlight is for sparse binary data we may want to rethink the {+1,-1} encoding convention. Consider applications where you are trying to detect sparse, binary events. Then I think it makes sense for the target to be a sparse vector and for us to interpret the zeros as `-1`s.

``` julia
using LossFunctions
t = [-1,1.]
t_sparse = sparse([0,1.])
x = randn(2);
value(LogitMarginLoss(),t,x)
2-element Array{Float64,1}:
 0.0806863
 0.0330961

value(LogitMarginLoss(),t_sparse,x)
2-element Array{Float64,1}:
 0.0454645
 0.0330961
```

There are a variety of efficiencies we could implement in this case as well.

**Comment by ahwillia** [comment]
This is somewhat ugly, and I haven't tested it yet, but something along these lines could work... 

```julia
##
# Function for sparse arrays
@generated function value!{T,N,Q,M}(
        buffer::AbstractArray,
        loss::BinarySupervisedLoss,
        target::AbstractSparseArray{Q,Ti,M},
        output::AbstractArray{T,N}
    )
    M > N && throw(ArgumentError("target has more dimensions than output; broadcasting not supported in this direction."))
    quote
      @_dimcheck size(buffer) == size(output)
      @nexprs $M (n)->@_dimcheck(size(target,n) == size(output,n))
      zeroM = zero(M)
      negM = M(-1)
      @simd for I in CartesianRange(size(output))
          @nexprs $N n->(i_n = I[n])
          tgt = @nref($M,target,i)
          if tgt == zeroM
              # convention is that zeros in a sparse array are interpreted as negative one
              @inbounds @nref($N,buffer,i) = value(loss, negM, @nref($N,output,i))
          else
              @inbounds @nref($N,buffer,i) = value(loss, tgt, @nref($N,output,i))
          end
      end
      buffer
    end
end
```

**Comment by Evizero** [comment]
Well, the {+1,-1} convention is a bit out of our hands and part of what defines a margin loss, so I am not sure I understand what you mean with rethink.

Concerning sparse and {1, 0}. It does make sense to offer this. Over at [MLMetrics.jl](https://github.com/JuliaML/MLMetrics.jl/blob/master/src/classification/comparemode.jl#L21-L25) I am experimenting with a fuzzy compare more, which allows tries to figure out what is positive and negative and can match {true, false}, {1, -1}, and {1, 0} with each other. That said that is a lot easier to realize when the convention is not part of the computation.

Maybe we can make some kind of decorator, similar to `ScaledLoss`?

**Comment by ahwillia** [comment]
Sorry by "rethink" I meant that we should consider interpreting zeros in a sparse array as `-1`

**Comment by ahwillia** [comment]
> Maybe we can make some kind of decorator, similar to ScaledLoss?

Interesting, how do you mean exactly?

**Comment by Evizero** [comment]
I don't know, really. Probably dispatching on SparseMatrix/Vector offers enough information.

**Comment by Evizero** [comment]
Well, or.. In MLMetrics I solve this with a optional type parameter. I can say `false_discovery_rate([true,false,true], [1,0,1], CompareMode.FuzzyBinary())` and it tries to infer what is positive or negative on the values themselves (on their own). This should work for us as well without a real performance overhead I think.

like `value(LogitMarginLoss(), [1, 0, 1], yhat, CompareMode.FuzzyBinary())`

**Comment by ahwillia** [comment]
The problem with my proposal is that we also need to dispatch on `BinaryLoss` or something along these lines. Which doesn't exist as of now.

**Comment by Evizero** [comment]
basically at the last moment it would swap out the value for `1` if it is deemed positive, such as true, or 1, and `-1` if it is not, such as -1, false, or 0

**Comment by Evizero** [comment]
What would that class represent?

**Comment by ahwillia** [comment]
> What would that class represent?

Any supervised loss whose targets are in `{-1,1}`. It is better represented as a trait, but no luck dispatching on those as far as I know.

**Comment by Evizero** [comment]
Fair enough. Practically speaking, MarginLoss should match all current losses in that category I think. Maybe the BinaryLoss question could be solved some other day independently of the SparseMatrix one

**Comment by ahwillia** [comment]
I suppose we might want to allow a user to input a dense vector, `target = [0.0, 0.0, 1.0]` and still map the zeros to neg ones... So I like something along the lines of `value(LogitMarginLoss(), [1, 0, 1], yhat, CompareMode.FuzzyBinary())`

Do you have the bandwidth to add this? I'm happy to help if you can get me started -- I want it to be consistent with what you've used elsewhere.

**Comment by ahwillia** [comment]
> Practically speaking, MarginLoss should match all current losses in that category I think. 

Except `LogitDistLoss` right?

**Comment by Evizero** [comment]
Nono, that is a distance-based version of the logistic loss for regression problems

**Comment by Evizero** [comment]
> Do you have the bandwidth to add this?

Not this week for certain. Plus MLMetrics is still in a volatile state. Short term it may be more fruitful to add some special SparseArray code as you proposed. But I will move the CompareMode code to LearnBase is the near future. It would make sense to allow this kinds of trickeries here as well

**Comment by ahwillia** [comment]
Yes, since I can dispatch on both `MarginLoss` and `AbstractSparseArray` then this should work... Though the best iteration pattern will depend on the type of sparse array. Do you think it makes sense for me to open a PR for this?

**Comment by Evizero** [comment]
> Do you think it makes sense for me to open a PR for this?

I leave the judgement to you. Do you work with this kind of problems currently? I am ok with leaving it undocumented for now (as long as it is tested enough) and we can see how it works out for your use-cases and adapt along the way
