### ISSUE TITLE
Add WeightedLosses

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaML/LossFunctions.jl#58]
Weighted losses seem to be more general than the loss functions considered here. I personally want it so that why I can also specify time-weighted regressions [like the two-stage method here](http://www.birs.ca/events/2013/5-day-workshops/13w5151/videos/watch/201311140905-Campbell.html) using the same infrastructure as LossFunctions.jl. Other places where this comes up are things like LOESS. It would be a very small expansion to the API to allow passing a weight vector (as optional, defaults to ones) and weight function, but it seems like it could have many uses.

**Comment by Evizero** [comment]
weighted in what sense? the individual observations?

**Comment by ChrisRackauckas** [comment]
Yes. Look at the equation for the two-stage method. Part of the loss function is a weight, where data points for later in time have a lower weight then those closer to the start time. This is generally just being able to define a weight function for the observations.

**Comment by Evizero** [comment]
With the new broadcast support one can do element-wise weighting strategies themselves

```
value.(L2DistLoss(), y, yhat .* weights)
value.(L2DistLoss(), y, yhat) .* weights
```

A weighted average mode will be added as soon as I have time to transfer the average modes and compare modes here from MLMetrics.

**Comment by Evizero** [comment]
weighted average mode in development here #71
