### ISSUE TITLE
Documentation of Loss properties

### ISSUE THREAD

**Issue by Evizero** [JuliaML/LossFunctions.jl#73]
It would maybe be nice to describe the implemented properties. For example the description for `isconvex` could state a short formal or informal definition for what makes a loss convex. etc

*note to self: link to places. add reference in contributing issue*

**Comment by kumarkrishna** [comment]
@Evizero Are you already working on this in the ```doc``` branch? Otherwise I could help in documenting these.

**Comment by Evizero** [comment]
Hey! Yea I am working on the doc branch, but not the loss properties. So I welcome your help if you fell like it. basically the properties are here https://github.com/JuliaML/LossFunctions.jl/blob/docs/docs/losses/interface.rst at the bottom.

**Comment by Evizero** [comment]
I created a `dev` branch to work on. I'll enable readthedocs there as well. Let us PR to that

**Comment by Evizero** [comment]
Current state http://lossesjl.readthedocs.io/en/dev/
