### ISSUE TITLE
Add regularization to loss functions

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaML/LossFunctions.jl#81]
It would be cool to be able to specify some function from https://github.com/JuliaML/PenaltyFunctions.jl to use as a regularization term in a loss function. This will make this setup able to capture most of the common loss functions more easily.

**Comment by Evizero** [comment]
Penalties are not part of the Loss as we see it. it is part of the structural risk, which is out of scope of this package and as such intended to be in its own. I just did not find the time to start it yet
