### ISSUE TITLE
Tackle last remaining deprecation warnings

### ISSUE THREAD

**Issue by joshday** [JuliaML/LossFunctions.jl#98]
I've been unable to figure out what's causing the last remaining warnings.

https://travis-ci.org/JuliaML/LossFunctions.jl/jobs/411444160

There's some stuff hidden inside functions or an eval that make it hard to find the source of the problem.  I thought I'd open an issue in case someone thinks they can figure it out.  I probably won't make another attempt until after JuliaCon.

**Comment by Evizero** [comment]
By the way, thanks a lot for all your effort in upgrading JuliaML stuff
